services:
  - type: web
    name: booking-website-martine
    runtime: node
    rootDir: booking-website
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
